# Generated by Django 2.2.7 on 2019-11-25 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='registro_ponto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('entrada', models.TimeField(auto_now_add=True)),
                ('intervalo', models.TimeField(auto_now_add=True)),
                ('retorno', models.TimeField(auto_now_add=True)),
                ('saida', models.TimeField(auto_now_add=True)),
                ('hora_extra', models.TimeField()),
                ('hora_negativa', models.TimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
