# Generated by Django 2.2.6 on 2019-10-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Registro', models.CharField(max_length=6)),
                ('Nome', models.CharField(max_length=30)),
                ('CPF', models.CharField(max_length=11)),
                ('Email', models.EmailField(max_length=254)),
                ('NomeDeUsuario', models.CharField(max_length=12)),
                ('Senha', models.CharField(max_length=12)),
                ('Perfil', models.CharField(max_length=12)),
                ('UltimoLogin', models.DateTimeField()),
                ('RecCreatedOn', models.DateTimeField()),
                ('RecCreatedBy', models.DateTimeField()),
                ('RecModifiedOn', models.DateTimeField()),
                ('RecModifiedBy', models.DateTimeField()),
            ],
        ),
    ]
