# Generated by Django 3.0 on 2019-12-05 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chamados_suporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=15)),
                ('tipo', models.CharField(max_length=15)),
                ('descricao', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='colaboradores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=50)),
                ('numero_registro', models.CharField(max_length=9)),
                ('cargo', models.CharField(max_length=12)),
                ('setor', models.CharField(max_length=12)),
                ('entrada', models.CharField(max_length=5)),
                ('intervalo', models.CharField(max_length=5)),
                ('retorno', models.CharField(max_length=5)),
                ('saida', models.CharField(max_length=5)),
                ('dias', models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='registro_ponto',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='registro_ponto',
            name='entrada',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='registro_ponto',
            name='hora_extra',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='registro_ponto',
            name='hora_negativa',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='registro_ponto',
            name='intervalo',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='registro_ponto',
            name='retorno',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='registro_ponto',
            name='saida',
            field=models.CharField(max_length=5),
        ),
        migrations.AddField(
            model_name='registro_ponto',
            name='colaborador',
            field=models.ForeignKey(db_column='nome_completo', default=0, on_delete=django.db.models.deletion.CASCADE, to='core.colaboradores'),
        ),
    ]
