# Generated by Django 2.2.6 on 2019-10-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=30)),
                ('Entrada', models.TextField()),
                ('Almoco', models.TextField()),
                ('Retorno', models.TextField()),
                ('Saida', models.TextField()),
                ('DataHora', models.DateTimeField(auto_now_add=True)),
                ('Credito', models.FloatField()),
                ('Debito', models.FloatField()),
                ('Status', models.BooleanField()),
                ('Aprovador', models.CharField(max_length=30)),
                ('DataAprovacao', models.DateTimeField()),
            ],
        ),
    ]
