# Generated by Django 3.0 on 2019-12-05 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191205_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_ponto',
            old_name='entrada',
            new_name='registro',
        ),
        migrations.RemoveField(
            model_name='registro_ponto',
            name='hora_extra',
        ),
        migrations.RemoveField(
            model_name='registro_ponto',
            name='hora_negativa',
        ),
        migrations.RemoveField(
            model_name='registro_ponto',
            name='intervalo',
        ),
        migrations.RemoveField(
            model_name='registro_ponto',
            name='retorno',
        ),
        migrations.RemoveField(
            model_name='registro_ponto',
            name='saida',
        ),
    ]
