# Generated by Django 3.0 on 2019-12-06 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191205_2256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chamados_suporte',
            new_name='ChamadosSuporte',
        ),
        migrations.RenameModel(
            old_name='registro_ponto',
            new_name='RegistroPonto',
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='colaborador',
            field=models.ForeignKey(db_column='nome_completo', default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Colaboradores'),
        ),
    ]
