# Generated by Django 3.0 on 2019-12-06 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191206_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='colaborador',
            field=models.ForeignKey(db_column='nome_completo', default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Colaboradores'),
        ),
    ]
