# Generated by Django 3.0 on 2019-12-06 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191206_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='gerente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='tipo_registro',
            field=models.CharField(default=0, max_length=9),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='colaborador',
            field=models.ForeignKey(db_column='nome_completo', default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Colaboradores'),
        ),
    ]
