# Generated by Django 3.0 on 2019-12-06 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191206_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroponto',
            name='registro',
        ),
        migrations.AddField(
            model_name='registroponto',
            name='dia',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='hora',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='colaborador',
            field=models.ForeignKey(db_column='nome_completo', default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Colaboradores'),
        ),
    ]
